# Generated by Django 3.0.5 on 2020-06-27 20:33

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200327_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
    ]
